### ISSUE TITLE
Documentation with HTML elements result in invalid SVGs

### ISSUE THREAD

**Issue by akutz** [Intelligent2013/xsdvi#9]
Consider the following:

```xml
        <xs:annotation>
            <xs:appinfo><meta:version added-in="5.1"/></xs:appinfo>
            <xs:documentation source="since">5.1</xs:documentation>
            <xs:documentation xml:lang="en">
               Locality parameters provide a hint that may help optimize
               placement of a VM with respect to another VM or an independent
               disk.
               See &lt;a href="http://kb.vmware.com/kb/2105352"&gt;KB 2105352&lt;/a&gt;.
            </xs:documentation>
        </xs:annotation>
```

The above results in the the generation of the following SVG content:

```xml
<g id='_1_84_1_1_2_3_1_2_3' class='box' transform='translate(1235,447634)' data-desc-height='448' data-desc-height-rest='448' data-desc-x='1235'>
<rect class='shadow' x='3' y='3' width='213' height='46'/>
<rect class='boxelementoptional' x='0' y='0' width='213' height='46'
/>
<text class='visible' x='5' y='13'>http://www.vmware.com/vcloud/v1.5</text>
<text class='strong elementlink' x='5' y='27'>LocalityParams</text>
<text class='visible' x='5' y='41'>type: LocalityParamsType</text>
<text x='5' y='59'>0..1</text>
<text x='5' y='73' class='desc'>always</text>
<text x='5' y='87' class='desc'></text>
<text x='5' y='101' class='desc'>                               </text>
<text x='5' y='115' class='desc'>Locality parameters provide a hint that</text>
<text x='5' y='129' class='desc'>may</text>
<text x='5' y='143' class='desc'>                               </text>
<text x='5' y='157' class='desc'>help optimize placement of a VM with</text>
<text x='5' y='171' class='desc'>respect to</text>
<text x='5' y='185' class='desc'>                            </text>
<text x='5' y='199' class='desc'>another VM or an independent disk.</text>
<text x='5' y='213' class='desc'>    </text>
<text x='5' y='227' class='desc'>See <a</text>
<text x='5' y='241' class='desc'>href="http://kb.vmware.com/kb/2105352"></text>
<text x='5' y='255' class='desc'>KB 2105352</a>.</text>
<text x='5' y='269' class='desc'>                       </text>
<text x='5' y='283' class='desc'>false</text>
<line class='connection' x1='-35' y1='23' x2='0' y2='23'/>
<use x='212' y='17' xlink:href='#minus' id='s_1_84_1_1_2_3_1_2_3' onclick='show("_1_84_1_1_2_3_1_2_3")'/>
</g>
```

Notice this part specifically:

```xml
<text x='5' y='227' class='desc'>See <a</text>
<text x='5' y='241' class='desc'>href="http://kb.vmware.com/kb/2105352"></text>
<text x='5' y='255' class='desc'>KB 2105352</a>.</text>
```

The above is invalid. Line by line:

* Line 1
    ```xml
    <text x='5' y='227' class='desc'>See <a</text>
    ```
    * The anchor tag `<a` tag is not closed.
    * The anchor tag is interrupted by the closing `</text> tag.

* Line 2
    ```xml
    <text x='5' y='241' class='desc'>href="http://kb.vmware.com/kb/2105352"></text>
    ```
    * The `href` attribute of the anchor tag is separated from the anchor tag.

* Line 3
    ```xml
    <text x='5' y='255' class='desc'>KB 2105352</a>.</text>
    ```
    * The closing anchor tag is separated from the rest of it.

Ultimately this results in an SVG that cannot be rendered.

**Comment by Intelligent2013** [comment]
@akutz thank you for pointing this out.
The issue fixed in the `xsdvi` version 1.2 https://github.com/metanorma/xsdvi/releases/tag/v1.2.

**Comment by akutz** [comment]
Let me try regenerating the file with the fix, and I'll let you know how it goes!

**Comment by akutz** [comment]
Thank you for trying, but it still does not work. Here's what the current build produces:

<img width="1037" alt="Image" src="https://github.com/user-attachments/assets/6733c7b5-9c6f-47f0-ad8e-b23323db51f6" />

Line 5883 is the third line in the snippet below:

```xml
<text x='5' y='269' class='desc'>See &lt;a</text>
<text x='5' y='283' class='desc'>                             </text>
<text x='5' y='297' class='desc'>href="http://kb.vmware.com/kb/2105352"&</text>
<text x='5' y='311' class='desc'>gt;KB</text>
```

You can see that it broke the `&gt;` across two `text` tags.

Maybe it would be good to add some unit tests to validate the fix? Here's the input for the broken section if you wanted to use it for some test:

```xml
                    <xs:element name="LocalityParams" type="LocalityParamsType"
                        minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:appinfo>
                                <meta:version added-in="INSTANTIATE_VM_TEMPLATE" />
                            </xs:appinfo>
                            <xs:documentation source="since">INSTANTIATE_VM_TEMPLATE</xs:documentation>
                            <xs:documentation source="modifiable">always</xs:documentation>
                            <xs:documentation xml:lang="en">
                                Locality parameters provide a hint that
                                may help optimize placement of a VM and
                                an independent a Disk so that the VM can
                                make efficient use of the disk.
                                See &lt;a
                                href="http://kb.vmware.com/kb/2105352"&gt;KB
                                2105352&lt;/a&gt;.
                            </xs:documentation>
                            <xs:documentation source="required">false</xs:documentation>
                        </xs:annotation>
                    </xs:element>
```

**Comment by Intelligent2013** [comment]
@akutz I've added the test `successProcessXMLEntitiesInDocumentationTag` and simple XSD https://github.com/metanorma/xsdvi/blob/master/src/test/resources/TestXMLEntities.xsd. Test passed OK.

Bug for the big XSD https://github.com/vmware/vcd-api-schemas/blob/master/schemas/rest-api/src/main/resources/etc/1.5/schemas/vcloud/vApp.xsd (found on GH by `xs:element name="LocalityParams" type="LocalityParamsType"`) I get the error:
![Image](https://github.com/user-attachments/assets/dda59a23-eccd-40ce-b4a4-cca42a004140)

I'll investigate what's happened.

**Comment by Intelligent2013** [comment]
@akutz please try `xsdvi` version 1.3 https://github.com/metanorma/xsdvi/releases/tag/v1.3.

**Comment by akutz** [comment]
@Intelligent2013 Will do, thank you. FYI, I would have shared the XSD directly, but I did not realize that those schemas were public. I was pulling them from an internal repo.

**Comment by akutz** [comment]
Perfect sir, thank you!
